### ISSUE TITLE
How do you build/run this project?

### ISSUE THREAD

**Issue by Kurren123** [fsprojects/FSharp.Data.GraphQL#131] opened 2017-09-22 10:12 UTC
Operating System: `Windows 10`
Dotnet version: `2.0.0`
Visual studio version: `Visual Studio 2017 15.3.5`
Microsoft Build Engine version: `15.3.409.57025`

If I do `build.cmd` paket restores successfully and the fsx file cleans successfully. But then when it tries to build it says:

`error MSB4019: The imported project "C:\Users\Kurren Nischal\Documents\Development stuff\F
       Sharp.Data.GraphQL\.paket\Paket.Restore.targets" was not found. Confirm that the path in the <Import> declaration is
       correct, and that the file exists on disk.`

When I try and open the solution in Visual Studio 2017 I also get that `Paket.Restore.targets` not found error.

If I do `paket install` then `dotnet build` everything builds except for the client project which comes back with `error MSB4020: The value "" of the "Project" attribute in element <Import> is invalid.`. Still unable to open these in Visual Studio or VS Code.

Any help would be greatly appreciated as I am [hoping to contribute](https://github.com/fsprojects/FSharp.Data.GraphQL/issues/132).

**Comment by Horusiath** [comment] 2017-09-22 11:20
This is more of the problem with Visual Studio and F# awareness in .NET ecosystem (similar thread: #123). I'm afraid that you may need to look for help in community forums (like F# slack channel) unless @TOTBWF have some procedure for working this problem out.

**Comment by Kurren123** [comment] 2017-09-22 11:46
@Horusiath  thanks for your reply. I'm happy to use vs code or any other editor, I'm just wondering how others manage to do it.

**Comment by TOTBWF** [comment] 2017-09-22 22:02
Try running `msbuild /t:restore` before running. Also, what branch are you on?

**Comment by zaaack** [comment] 2017-09-28 09:21
@Kurren123  I'm using macos + ionide for vscode, try to working on the dev branch, got same issue in client project and work it around by adding these lines in `Otherwise` xml node, but then got another error. What's more, there are also many errors in test projects.
```sh
<PropertyGroup Condition="Exists('/usr/local/share/dotnet/sdk/2.0.0/FSharp/Microsoft.FSharp.Targets')"> 
  <FSharpTargetsPath>/usr/local/share/dotnet/sdk/2.0.0/FSharp/Microsoft.FSharp.Targets</FSharpTargetsPath>
</PropertyGroup>
```
I don't think these could be easily solved by a newbie like me... I have some ideas to make the client type provider more extensible, but getting stuck in the editor issue, hoping someone could help. 😄 

@TOTBWF  I tried, no lucky. BTW, I can successfully build it in my macos, just editor, neither vscode nor vs for mac could work.
https://github.com/ionide/ionide-vscode-fsharp/issues/564

**Comment by enricosada** [comment] 2017-10-03 10:48
@zaaack i can repro doing `build Build` on a clean repo.
i asked paket team, the `Paket.Restore.targets` must be committed in the repository. that's by design (ref https://github.com/fsprojects/Paket/issues/2817 )

you can workaround now running `paket install` who create the target file. (`dotnet restore` or `paket restore` or boostrapping does do that)

Also, old fsproj cannot reference new fsproj. that's not supported atm pratically by anyone. project loading with fail on all FSAC based (ioniode/vim/emacs) and VS doesnt work yet with new sdk.
So or new format, or new and old in parallel (multiple fsproj)

I can send a PR fixing the fsprojs for new sdk and the build.

Is ok to use thew new sdk (the new fsproj) only? that mean no Visual Studio for now (new sdk is not supported there).
But will work on others (ionode/vim/emacs/rider/vs4mac).

Is that ok? otherwise you can add .net core as additional project, so maintain both

@zaaack Just tell me what to do:

- replace old sdk with new one (you lose VS as editor)
- use both, so duplicated files and more maintenance, but vs will continue to work

**Comment by enricosada** [comment] 2017-10-03 14:14
@zaaack appeveyor seems disabled. 
i openeded https://github.com/fsprojects/FSharp.Data.GraphQL/pull/137 with an empty commit to test that.

atm in windows the repo doesnt build running `build Build`

@Horusiath @TOTBWF can you reenable appveyor please? i'll fix it

**Comment by johnberzy-bazinga** [comment] 2017-10-11 23:33
@enricosada I've enabled appveyor and updated appveyor's config to use the VS 2017 image. Also, the badges in the Readme are now updated to reflect the CI changes.

Thanks,
John

**Comment by Zeroto** [comment] 2017-11-14 13:11
@enricosada Did you make any progress with making the build work? I'm having a lot of problems getting the build to work. e.g. `dotnet restore` gives errors like this: `error NU1100: Unable to resolve 'FSharp.NET.Sdk (>= 1.0.0)' for '.NETFramework,Version=v4.6/win7-x86'`. And without `dotnet restore` it doesn't build because of unrestored dependencies.

**Comment by johnberzy-bazinga** [comment] 2017-11-14 19:01
@Zeroto I've made some progress on the build. Do you want to try off of my fork?
 https://github.com/johnberzy-bazinga/FSharp.Data.GraphQL

Thanks,
John

**Comment by johnberzy-bazinga** [comment] 2019-05-14 03:57
This should work now. Just use build.cmd or build.sh.

**Closed as completed by johnberzy-bazinga** 2019-05-14 03:57 UTC
