### ISSUE TITLE
Missing namespace/module with 1.0.0-beta9

### ISSUE THREAD

**Issue by Swoorup** [fsprojects/FSharp.Data.GraphQL#229] opened 2019-05-27 03:02 UTC
### Description

Using `FSharp.Data.GraphQL.Server.Middlewares` gives `The namepace Middlewares is not defined`.

### Repro steps

1. Create a sample project or copy the sample starwars example.

2. Install both Server and Middlewares packages via Nuget both specifically 1.0.0-beta9

3. Observe the compiler error.

![image](https://user-images.githubusercontent.com/3408009/58392892-b6043e00-806e-11e9-8fca-b74e82b6f5f0.png)

### Known workarounds

Installing 1.0.0-beta8 for the middleware package appears to work fine.

**Comment by ivelten** [comment] 2019-06-21 22:07
@Swoorup that was actually an issue caused by a design change in the paket template, in which we accidentaly removed the command to add the dll reference when installing the package. The fix is in #228 ([this commit](https://github.com/fsprojects/FSharp.Data.GraphQL/pull/228/commits/852c21d9c9eb139d62965a3cc2684f46c1504005), to be more precise). We will be releasing it soon, hopefully next week. Thanks.

**Comment by johnberzy-bazinga** [comment] 2019-07-14 21:19
This should be fixed now. Please let us know if you're still experiencing issues.

**Closed as completed by johnberzy-bazinga** 2019-07-14 21:19 UTC
